type Lolly {
    id: ID!
    recipient: String!
    message: String!
    sender: String!
    c1: String!
    c2: String!
    c3: String!
    link: String!
}

input LollyInput {
    recipient: String!
    message: String!
    sender: String!
    c1: String!
    c2: String!
    c3: String!
    link: String!
}


type Query{
    getLollies: [Lolly!]
    getLollyByID(id: String!): Lolly!

}

type Mutation{
    # createLolly(recipient: String! message: String! sender: String! c1: String! c2: String! c3: String!): Lolly
    createLolly(LollyInfo: LollyInput): Lolly
    deleteLolly(id: String): Lolly

}