type Lolly {
    id: ID!
    recipient: String!
    message: String!
    sender: String!
    c1: String!
    c2: String!
    c3: String!
    link: ID!
  }

input LollyInput{
      recipient: String!, 
      message: String!,
      sender: String!, 
      c1: String!,
      c2: String!,
      c3: String!
      link: String!
}


type Query{
    getLollies: [Lolly!]
    getLollybyID(id: String!): Lolly!
    getLollybyLink(link: String!): Lolly!
}

type Mutation {
    createLolly (
      recipient: String!, 
      message: String!,
      sender: String!, 
      c1: String!,
      c2: String!,
      c3: String!
      link: String!) : Lolly


      deleteLolly(id: String!): Lolly!
}